apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
spec:
  interval: 10m
  path: ./zz_generated/public1/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: public-infrastructure
