apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infra-read-source
  namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infra-read
subjects:
- kind: ServiceAccount
  name: source-controller
  namespace: flux-system
