apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hik8s-system

resources:
  - namespace.yaml
  - secret.yaml

helmCharts:
  - name: hik8s-system
    repo: https://chart.atenia.ai/
    version: v0.1.4
    releaseName: hik8s
    namespace: hik8s-system-stag
    valuesInline:
      auth:
        createSecret: false
      dataIntake:
        endpoint: api.hik8s.ai
      logd:
        imageVersion: 0.2.3
      watchd:
        imageVersion: 0.1.0
