repos:
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--exclude-lines', 'ENC', '--exclude-secrets', '7C3D956BFD6132ABE9B3BDA354C36FA156D8BD5F', '--exclude-secrets', '785D5B82A4F4BC64AF83CE3FB6AF197DF6CBC418']  
