apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: flux-system
  name: sops-gpg
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["sops-gpg"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: flux-system
  name: sops-gpg-kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sops-gpg
subjects:
- kind: ServiceAccount
  name: kustomize-controller
  namespace: flux-system
