apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: public-infrastructure
  path: ./source-of-truth/public1/system
  prune: true
