apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logd
  namespace: hik8s-system
spec:
  selector:
    matchLabels:
      name: logd
  template:
    metadata:
      labels:
        name: logd
    spec:
      containers:
      - env:
        - name: RUST_LOG
          value: info
        - name: BASE_URL
          value: https://api.hik8s.ai
        - name: AUTH0_AUDIENCE
          value: api.hik8s.ai
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: clientid
              name: hik8s-credentials
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: clientsecret
              name: hik8s-credentials
        - name: AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              key: auth0domain
              name: hik8s-credentials
        image: ghcr.io/hik8s/logd:0.2.0
        name: logd
        volumeMounts:
        - mountPath: /var/log/pods
          name: log-directory
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      volumes:
      - hostPath:
          path: /var/log/pods
          type: Directory
        name: log-directory
