apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-viewer
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - namespaces
  - nodes
  - serviceaccounts
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  - certificates
  - issuers
  - clusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - acme.cert-manager.io
  resources:
  - challenges
  - orders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fluvio.infinyon.com
  resources:
  - mirrors
  - partitions
  - smartmodules
  - spugroups
  - spus
  - tableformats
  - topics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - reports.kyverno.io
  resources:
  - clusterephemeralreports
  - ephemeralreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cilium.io
  resources:
  - ciliumbgpadvertisements
  - ciliumbgpclusterconfigs
  - ciliumbgpnodeconfigoverrides
  - ciliumbgpnodeconfigs
  - ciliumbgppeerconfigs
  - ciliumbgppeeringpolicies
  - ciliumcidrgroups
  - ciliumclusterwideenvoyconfigs
  - ciliumclusterwidenetworkpolicies
  - ciliumendpoints
  - ciliumenvoyconfigs
  - ciliumexternalworkloads
  - ciliumidentities
  - ciliuml2announcementpolicies
  - ciliumloadbalancerippools
  - ciliumnetworkpolicies
  - ciliumnodeconfigs
  - ciliumnodes
  - ciliumpodippools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kyverno.io
  resources:
  - admissionreports
  - backgroundscanreports
  - cleanuppolicies
  - clusteradmissionreports
  - clusterbackgroundscanreports
  - clustercleanuppolicies
  - clusterpolicies
  - globalcontextentries
  - policies
  - policyexceptions
  - updaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - alerts
  - providers
  - receivers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image.toolkit.fluxcd.io
  resources:
  - imagepolicies
  - imagerepositories
  - imageupdateautomations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wgpolicyk8s.io
  resources:
  - clusterpolicyreports
  - policyreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets
  - gitrepositories
  - helmcharts
  - helmrepositories
  - ocirepositories
  verbs:
  - get
  - list
  - watch
