apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: flux-system
  name: sops-gpg
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["sops-gpg"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: flux-system
  name: infra-read
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["hik8s-bot-infra-read-token"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: flux-system
  name: sops-gpg-kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sops-gpg
subjects:
- kind: ServiceAccount
  name: kustomize-controller
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: flux-system
  name: infra-read-source
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infra-read
subjects:
- kind: ServiceAccount
  name: source-controller
  namespace: flux-system