apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - control-plane-network-policy.yaml

helmCharts:
  - name: cilium
    releaseName: cilium
    repo: https://helm.cilium.io/
    version: 1.16.0
    namespace: kube-system
    valuesFile: cilium-values.yaml

patches:
  - path: patches/operator-scale-down-replicas.yaml
