apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cilium
    releaseName: cilium
    repo: https://helm.cilium.io/
    version: 1.15.6
    namespace: kube-system
    valuesFile: cilium-values.yaml

patches:
  - path: patches/operator-scale-down-replicas.yaml
