apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: system
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m
  path: ./source-of-truth/public1/system
  prune: true
  sourceRef:
    kind: GitRepository
    name: public-infrastructure
