apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sops-gpg-kustomize
  namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sops-gpg
subjects:
- kind: ServiceAccount
  name: kustomize-controller
  namespace: flux-system
